#!/bin/bash

FOLDER="/home/stefan/myarchconfig/"
PREKILL=home/stefan/

echo "copy"
echo

echo > "${FOLDER}.files"

while IFS= read -r FILE; do
  [[ ! $FILE == \#* ]] && {
    BASE=${FILE##*/}
    BASE=${BASE#.}
    [[ $BASE == *"*"* ]] && BASE=""
    DIR=""
    {
      DIR=${FILE%/*}
      DIR=${DIR#*/}"/"
      DIR=${DIR##$PREKILL}
      DIR=${DIR#.}
    }
    mkdir -p "${FOLDER}${DIR}"
    cp -vu $FILE "${FOLDER}${DIR}${BASE}"

    echo "${DIR}${BASE}    $FILE" >> "${FOLDER}.files"
    #echo "$FILE -> $FOLDER$DIR$BASE"
  }
done <<EOF
/home/stefan/.Xresources
/home/stefan/.vimrc
/home/stefan/.zprofile
/home/stefan/.zshrc.local
/home/stefan/.zshrc
/home/stefan/.latexmkrc
/home/stefan/.xinitrc
/home/stefan/.xmonad/xmonad.hs
/home/stefan/.xmonad/xmobarrc
/home/stefan/.xbindkeysrc
/home/stefan/.asoundrc
/home/stefan/.asoundrc.asoundconf
/home/stefan/bin/myinformation.sh
/home/stefan/bin/ncChat.sh
/etc/X11/xorg.conf.d/10-evdev.conf
/etc/X11/xorg.conf.d/10-quirks.conf
/etc/X11/xorg.conf.d/20-intel.conf
/etc/X11/xorg.conf.d/20-keyboard.conf
/etc/X11/xorg.conf.d/50-synaptics.conf
/etc/modprobe.d/blacklist.conf
/etc/pam.d/passwd
/etc/pam.d/system-auth
/etc/security/pam_encfs.conf
/etc/fuse.conf
/home/stefan/.muttrc
/home/stefan/.offlineimaprc
/home/stefan/.mailcap
EOF

echo
echo "git"
echo

#cd "$FOLDER"
#git add .
#git commit -a -m "aktualisiert"
#git push
